Repository SuperDARN/rst, pull requests merged in 2019-06, with the labels that each got.

#220 Time fix
  codebase/general/src.lib/time.1.7/src/time.c
Labels: bug

#229 radar.dat update
  tables/superdarn/radar.dat
Labels: documentation

#93 Adding new elevation angle algorithm; keeping old with a new command line option
  codebase/superdarn/src.bin/tk/testing/fitcomp.1.0/fitcomp.c
  codebase/superdarn/src.bin/tk/testing/fitcomp.1.0/makefile
  codebase/superdarn/src.bin/tk/tool/make_fit.1.19/doc/make_fit.doc.xml
  codebase/superdarn/src.bin/tk/tool/make_fit.1.19/make_fit.c
  codebase/superdarn/src.bin/tk/tool/make_fit.1.19/makefile
  codebase/superdarn/src.bin/tk/tool/make_fitex2.1.0/makefile
  codebase/superdarn/src.bin/tk/tool/make_lmfit.1.0/makefile
  codebase/superdarn/src.lib/tk/elevation.1.0/include/elevation.h
  codebase/superdarn/src.lib/tk/elevation.1.0/src/elev_goose.c
  codebase/superdarn/src.lib/tk/elevation.1.0/src/elevation.c
  codebase/superdarn/src.lib/tk/elevation.1.0/src/elevation_v2.c
  codebase/superdarn/src.lib/tk/elevation.1.0/src/makefile
  codebase/superdarn/src.lib/tk/fitacf.2.5/include/dofit.h
  codebase/superdarn/src.lib/tk/fitacf.2.5/include/fitblk.h
  codebase/superdarn/src.lib/tk/fitacf.2.5/src/do_fit.c
  codebase/superdarn/src.lib/tk/fitacf.2.5/src/elevation.h
  codebase/superdarn/src.lib/tk/fitacf.2.5/src/fitacf.c
  codebase/superdarn/src.lib/tk/fitacf.2.5/src/makefile
  codebase/superdarn/src.lib/tk/fitacfex2.1.0/src/fitacfex2.c
Labels: enhancement

#221 Fixing segmentation fault in dmap.c when dmap array dimension value is corrupted
  codebase/general/src.lib/dmap.1.25/src/dmap.c
Labels: bug, high priority

#234 Modifying OldFitWrite of fitwrite.c in the oldfit library to store the offset value in usr_resL1
  codebase/superdarn/src.lib/tk/oldfit.1.25/src/fitwrite.c
Labels: bug

#232 IDL and DLM bug fixes
  codebase/superdarn/src.dlm/fitdlm.1.7/fitdlm.dlm
  codebase/superdarn/src.dlm/rposdlm.1.9/rposdlm.c
  codebase/superdarn/src.idl/lib/main.1.25/radar.pro
Labels: bug

#218 Fixing bug in solve_model.c when determining longitude spacing for equal-area grid
  codebase/superdarn/src.bin/tk/tool/solve_model.1.0/solve_model.c
Labels: bug

#228 Adding shortcuts to commonly used binaries on documentation front page
  build/doc/sk/doc.root.local.sk
Labels: documentation, enhancement
