Repository SuperDARN/rst, pull requests merged in 2020-09, with the labels that each got.

#321 Fixing DLM version of OldRawOpen
  codebase/superdarn/src.dlm/oldrawdlm.1.7/oldrawdlm.c
Labels: bug

#332 Fix max FOV range in plotting routines to 75 range gates
  codebase/superdarn/src.bin/tk/plot/field_plot.1.12/make_fov.c
  codebase/superdarn/src.bin/tk/plot/fov_plot.1.10/make_fov.c
  codebase/superdarn/src.bin/tk/plot/grid_plot.1.12/make_fov.c
  codebase/superdarn/src.bin/tk/plot/map_plot.1.12/make_fov.c
Labels: bug

#331 Fixing bug in grid_plot and map_plot preventing power or spectral width cells from being drawn for SH data
  codebase/superdarn/src.bin/tk/plot/grid_plot.1.12/grid_plot.c
  codebase/superdarn/src.bin/tk/plot/grid_plot.1.12/plot_cell.c
  codebase/superdarn/src.bin/tk/plot/map_plot.1.12/plot_cell.c
Labels: bug

#342 Citing data
  README.md
  docs/index.md
  docs/user_guide/citing.md
  docs/user_guide/data.md
  mkdocs.yml
Labels: documentation

#313 RAWACF documentation
  docs/references/general/rawacf.md
Labels: documentation, help wanted, high priority

#340 Fix/fitacf old
  codebase/superdarn/src.bin/tk/tool/make_fit.1.19/make_fit.c
Labels: bug, high priority
