Repository SuperDARN/rst, pull requests merged in 2020-10, with the labels that each got.

#327 combine_snd and updates to sounding library
  codebase/superdarn/src.bin/tk/plot/time_plot.1.8/snd.c
  codebase/superdarn/src.bin/tk/tool/combine_snd.1.0/combine_snd.c
  codebase/superdarn/src.bin/tk/tool/combine_snd.1.0/doc/combine_snd.doc.xml
  codebase/superdarn/src.bin/tk/tool/combine_snd.1.0/makefile
  codebase/superdarn/src.idl/lib/main.1.25/snd.pro
  codebase/superdarn/src.lib/tk/idl/sndidl.1.0/include/sndidl.h
  codebase/superdarn/src.lib/tk/idl/sndidl.1.0/src/sndidl.c
  codebase/superdarn/src.lib/tk/snd.1.0/doc/snd.doc.xml
  codebase/superdarn/src.lib/tk/snd.1.0/include/snddata.h
  codebase/superdarn/src.lib/tk/snd.1.0/src/fitsnd.c
  codebase/superdarn/src.lib/tk/snd.1.0/src/sndread.c
  codebase/superdarn/src.lib/tk/snd.1.0/src/sndscan.c
  codebase/superdarn/src.lib/tk/snd.1.0/src/sndwrite.c
Labels: enhancement

#349 Modifying time_plot to more accurately plot range-time cells for SND-format data
  codebase/superdarn/src.bin/tk/plot/time_plot.1.8/snd.c
  codebase/superdarn/src.bin/tk/plot/time_plot.1.8/time_plot.c
Labels: bug

#346 Fixing bug in IDL DLM code when acfd array is missing
  codebase/superdarn/src.lib/tk/idl/rawidl.1.5/src/rawidl.c
Labels: bug

#351 feature/rtsnd
  codebase/superdarn/src.bin/tk/tool/rtsnd.1.0/doc/rtsnd.doc.xml
  codebase/superdarn/src.bin/tk/tool/rtsnd.1.0/loginfo.c
  codebase/superdarn/src.bin/tk/tool/rtsnd.1.0/loginfo.h
  codebase/superdarn/src.bin/tk/tool/rtsnd.1.0/makefile
  codebase/superdarn/src.bin/tk/tool/rtsnd.1.0/rtsnd.c
Labels: enhancement

#354 Fixing GRID scalar table
  docs/references/general/grid.md
Labels: documentation

#337 EHN/removing warnings
  build/make/makebin.linux
  build/make/makelib.linux
  codebase/analysis/src.bin/cdf/istp_plot.1.11/istp_plot.c
  codebase/analysis/src.bin/cdf/istp_text.1.24/istp_text.c
  codebase/analysis/src.lib/cdf/rcdf.1.5/src/rcdf.c
  codebase/analysis/src.lib/mlt/mlt.1.4/src/mlt.c
  codebase/base/src.bin/graphic/padxml.1.2/padxml.c
  codebase/base/src.bin/graphic/pngtoxml.1.3/pngtoxml.c
  codebase/base/src.bin/graphic/ppmtoxml.1.6/ppmtoxml.c
  codebase/base/src.bin/graphic/ppmxtoxml.1.4/ppmxtoxml.c
  codebase/base/src.bin/graphic/scalexml.1.7/scalexml.c
  codebase/base/src.bin/graphic/xmld.1.7/xmld.c
  codebase/base/src.bin/tcpip/ipserver.1.12/socket.c
  codebase/base/src.lib/graphic/fbuffer.1.19/src/char.c
  codebase/base/src.lib/graphic/fbuffer.1.19/src/ppm.c
  codebase/base/src.lib/graphic/imagedb.1.4/src/imagedb.c
  codebase/base/src.lib/graphic/iplotlib.1.4/src/make.c
  codebase/base/src.lib/graphic/ps.1.9/src/make.c
  codebase/base/src.lib/graphic/splotlib.1.3/src/make.c
  codebase/base/src.lib/xml/xmldoclib.1.5/src/make.c
  codebase/general/src.bin/task/eval.1.4/eval.c
  codebase/general/src.bin/tcpip/buffer_server.1.14/buffer_server.c
  codebase/general/src.bin/tcpip/rtmultiplex.1.32/socket.c
  codebase/general/src.bin/tcpip/rtpoll.1.15/rtpoll.c
  codebase/general/src.lib/dmap.1.25/src/merge.c
  codebase/general/src.lib/evallib.1.4/doc/src/Eval/Eval.c
  codebase/general/src.lib/evallib.1.4/src/eval.c
  codebase/imagery/src.lib/szamap.1.11/src/szamap.c
  codebase/superdarn/src.bin/tk/plot/field_plot.1.12/expr.c
  codebase/superdarn/src.bin/tk/plot/field_plot.1.12/field_plot.c
  codebase/superdarn/src.bin/tk/plot/fov_plot.1.10/fov_plot.c
  codebase/superdarn/src.bin/tk/plot/hmb_plot.1.6/hmb_plot.c
  codebase/superdarn/src.bin/tk/plot/pc_plot.1.6/pc_plot.c
  codebase/superdarn/src.bin/tk/plot/time_plot.1.8/expr.c
  codebase/superdarn/src.bin/tk/plot/time_plot.1.8/time_plot.c
  codebase/superdarn/src.bin/tk/plot/vec_plot.1.9/vec_plot.c
  codebase/superdarn/src.bin/tk/tcpip/fitacfclientscan.1.9/downloadscan.c
  codebase/superdarn/src.bin/tk/tcpip/fitacfserver.1.17/socket.c
  codebase/superdarn/src.bin/tk/tcpip/rtfitacftofit.1.19/socket.c
  codebase/superdarn/src.bin/tk/tcpip/rtfittofitacf.1.20/socket.c
  codebase/superdarn/src.bin/tk/tool/sim_real.1.0/sim_real.c
  codebase/superdarn/src.lib/tk/binplotlib.1.0/src/geobeam.c
  codebase/superdarn/src.lib/tk/cnvmodel.1.0/src/cnvmodel.c
  codebase/superdarn/src.lib/tk/fit.1.35/src/fit.c
  codebase/superdarn/src.lib/tk/fitacf.2.5/src/fit_acf.c
  codebase/superdarn/src.lib/tk/fitacf.2.5/src/fitacf.c
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/determinations.h
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/preprocessing.c
  codebase/superdarn/src.lib/tk/fitacfex2.1.0/src/fitacfex2.c
  codebase/superdarn/src.lib/tk/iq.1.7/src/iq.c
  codebase/superdarn/src.lib/tk/lmfit.1.0/src/lmfit.c
  codebase/superdarn/src.lib/tk/oldgrid.1.3/src/oldwritegrid.c
  codebase/superdarn/src.lib/tk/radar.1.22/src/radar.c
  codebase/superdarn/src.lib/tk/radar.1.22/src/rprm.c
  codebase/superdarn/src.lib/tk/raw.1.22/src/raw.c
  codebase/superdarn/src.lib/tk/rpos.1.7/src/invmag.c
Labels: Error/Warning checks, enhancement
