Repository SuperDARN/rst, pull requests merged in 2021-06, with the labels that each got.

#428 Fix/cdf not handled
  codebase/analysis/src.lib/cdf/rcdf.1.5/src/rcdf.c
Labels: bug

#429 Fixing error when using fov_plot
  codebase/superdarn/src.lib/tk/binplotlib.1.0/include/make_fov.h
Labels: bug

#427 Consolidating some elevation angle code in FITACF 3.0
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/determinations.c
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/determinations.h
Labels: bug

#430 Fixing bug in native IDL OldGridRead function
  codebase/superdarn/src.idl/lib/main.1.25/oldgrd.pro
Labels: bug

#437 MLT_v2 DLM inverse keyword
  codebase/analysis/src.dlm/aacgmdlm.2.0/aacgmdlm.dlm
  codebase/analysis/src.dlm/igrfdlm.1.3/igrfdlm.dlm
  codebase/analysis/src.dlm/mltdlm.2.0/mltdlm.c
  codebase/analysis/src.dlm/mltdlm.2.0/mltdlm.dlm
  codebase/superdarn/src.dlm/cnvmapdlm.1.7/cnvmapdlm.dlm
  codebase/superdarn/src.dlm/fitdlm.1.7/fitdlm.dlm
  codebase/superdarn/src.dlm/grddlm.1.7/grddlm.dlm
  codebase/superdarn/src.dlm/iqdlm.1.6/iqdlm.dlm
  codebase/superdarn/src.dlm/oldcnvmapdlm.1.4/oldcnvmapdlm.dlm
  codebase/superdarn/src.dlm/oldfitdlm.1.8/oldfitdlm.dlm
  codebase/superdarn/src.dlm/oldgrddlm.1.6/oldgrddlm.dlm
  codebase/superdarn/src.dlm/oldrawdlm.1.7/oldrawdlm.dlm
  codebase/superdarn/src.dlm/rawdlm.1.7/rawdlm.dlm
  codebase/superdarn/src.dlm/rposdlm.1.9/rposdlm.dlm
Labels: bug, enhancement

#439 More fixes to fov_plot
  codebase/superdarn/src.bin/tk/plot/fov_plot.1.10/doc/fov_plot.doc.xml
  codebase/superdarn/src.bin/tk/plot/fov_plot.1.10/fov_plot.c
  codebase/superdarn/src.bin/tk/plot/fov_plot.1.10/makefile
  codebase/superdarn/src.bin/tk/plot/fov_plot.1.10/plot_time.c
  codebase/superdarn/src.bin/tk/plot/fov_plot.1.10/plot_time.h
Labels: bug, enhancement

#420 Revising the noise calculation in FITACF3.0
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/preprocessing.c
Labels: bug, enhancement

#379 fixed the swap issue in time_plot
  codebase/superdarn/src.bin/tk/plot/time_plot.1.8/time_plot.c
Labels: Scientist input

#397 [FIX] grid_plot set delay 0
  codebase/superdarn/src.bin/tk/plot/field_plot.1.12/doc/field_plot.doc.xml
  codebase/superdarn/src.bin/tk/plot/field_plot.1.12/field_plot.c
  codebase/superdarn/src.bin/tk/plot/grid_plot.1.12/doc/grid_plot.doc.xml
  codebase/superdarn/src.bin/tk/plot/grid_plot.1.12/grid_plot.c
  codebase/superdarn/src.bin/tk/plot/iqplot.1.6/doc/iqplot.doc.xml
  codebase/superdarn/src.bin/tk/plot/iqplot.1.6/iqplot.c
  codebase/superdarn/src.bin/tk/plot/map_plot.1.12/doc/map_plot.doc.xml
  codebase/superdarn/src.bin/tk/plot/map_plot.1.12/map_plot.c
Labels: bug

#440 Multi-radar FOV plots with fov_plot
  codebase/superdarn/src.bin/tk/plot/fov_plot.1.10/doc/fov_plot.doc.xml
  codebase/superdarn/src.bin/tk/plot/fov_plot.1.10/fov_plot.c
Labels: enhancement
