Repository SuperDARN/rst, pull requests merged in 2021-05, with the labels that each got.

#398 Update instructions for map_addimf in readthedocs
  docs/user_guide/map_grid.md
Labels: documentation

#416 Fix undeclared variable in FITACF2.5
  codebase/superdarn/src.lib/tk/fitacf.2.5/src/do_fit.c
Labels: bug

#382 Developer Documentation on workflow
  docs/dev/branching.md
  docs/dev/cfit_struct_c.md
  docs/dev/cnvmap_struct_c.md
  docs/dev/cnvmap_struct_idl.md
  docs/dev/code_reviews.md
  docs/dev/communication.md
  docs/dev/copyright_license.md
  docs/dev/feature.md
  docs/dev/fitacf_struct_c.md
  docs/dev/fitacf_struct_idl.md
  docs/dev/grid_struct_c.md
  docs/dev/grid_struct_idl.md
  docs/dev/iqdat_struct_c.md
  docs/dev/iqdat_struct_idl.md
  docs/dev/issues.md
  docs/dev/projects.md
  docs/dev/pull_request.md
  docs/dev/radar_parameter_c.md
  docs/dev/radar_parameter_idl.md
  docs/dev/rawacf_struct_c.md
  docs/dev/rawacf_struct_idl.md
  docs/dev/releases.md
  docs/dev/testing.md
  docs/dev/workflow.md
  docs/index.md
  mkdocs.yml
Labels: documentation

#400 Routine to remove noise/interference from FITACF files
  codebase/superdarn/src.bin/tk/tool/fit_speck_removal.1.0/doc/fit_speck_removal.doc.xml
  codebase/superdarn/src.bin/tk/tool/fit_speck_removal.1.0/fit_speck_removal.c
  codebase/superdarn/src.bin/tk/tool/fit_speck_removal.1.0/makefile
Labels: enhancement

#421 Remove unnecessary fprintf statements from FITACF 3.0
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/determinations.c
Labels: bug
