Repository SuperDARN/rst, pull requests merged in 2021-02, with the labels that each got.

#356 Simon's elevation code into fitacf 3.0
  codebase/superdarn/src.bin/tk/tool/make_fit.1.19/make_fit.c
  codebase/superdarn/src.lib/tk/elevation.1.0/src/elevation_v2.c
  codebase/superdarn/src.lib/tk/fitacf.2.5/include/fitblk.h
  codebase/superdarn/src.lib/tk/fitacf.2.5/src/do_fit.c
  codebase/superdarn/src.lib/tk/fitacf_v3.0/include/fit_structures.h
  codebase/superdarn/src.lib/tk/fitacf_v3.0/include/fitacftoplevel.h
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/determinations.c
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/determinations.h
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/fitacftoplevel.c
Labels: Scientist input

#384 Developer Workflow Documentation: pull requests
  docs/dev/branching.md
  docs/dev/pull_request.md
Labels: documentation

#380 RST developer guide: Issues workflow
  docs/dev/issues.md
Labels: documentation

#374 adding dat documentation
  docs/index.md
  docs/references/general/dat.md
  mkdocs.yml
Labels: documentation

#364 Adding missing chisham keyword to RadarFldPnth in native IDL RadarPos function
  codebase/superdarn/src.idl/lib/main.1.25/radar.pro
Labels: bug

#386 Developer Workflow Documentation: Code Review
  docs/dev/code_reviews.md
Labels: documentation

#377 Doc/rfc content move
  build/doc/sk/rfc.inx.local.sk
  build/doc/sk/rfc.inx.www.sk
  docs/developers_guide/cfit_struct_c.md
  docs/developers_guide/cnvmap_struct_c.md
  docs/developers_guide/cnvmap_struct_idl.md
  docs/developers_guide/fitacf_struct_c.md
  docs/developers_guide/fitacf_struct_idl.md
  docs/developers_guide/grid_struct_c.md
  docs/developers_guide/grid_struct_idl.md
  docs/developers_guide/iqdat_struct_c.md
  docs/developers_guide/iqdat_struct_idl.md
  docs/developers_guide/radar_parameter_c.md
  docs/developers_guide/radar_parameter_idl.md
  docs/developers_guide/rawacf_struct_c.md
  docs/developers_guide/rawacf_struct_idl.md
  docs/index.md
  docs/legacy_software/efield_struct_idl.md
  docs/legacy_software/rPlot_XML.md
  docs/legacy_software/rPlot_lib.md
  docs/references/general/cfit.md
  docs/references/general/dmap_data.md
  docs/references/general/filename.md
  docs/references/general/fitacf.md
  docs/references/general/grid.md
  docs/references/general/iqdat.md
  docs/references/general/map.md
  docs/references/general/radar_id.md
  docs/references/general/radar_table.md
  mkdocs.yml
Labels: documentation

#391 Add missing "-ftrmcol" command line option to fov_plot
  codebase/superdarn/src.bin/tk/plot/fov_plot.1.10/fov_plot.c
Labels: bug, low priority
