Repository SuperDARN/rst, pull requests merged in 2021-03, with the labels that each got.

#388 GPLv3 license and copyright information for developers
  docs/developers_guide/copyright_license.md
Labels: documentation

#395 Fix bug in trim_raw
  codebase/superdarn/src.bin/tk/tool/trim_raw.1.15/trim_raw.c
Labels: bug, high priority

#328 fitacf 3.0 minimal refactor
  codebase/general/src.bin/tcpip/rtmultiplex.1.32/socket.c
  codebase/superdarn/src.bin/tk/tcpip/rtfitacftofit.1.19/socket.c
  codebase/superdarn/src.bin/tk/tool/make_fit.1.19/make_fit.c
  codebase/superdarn/src.lib/tk/elevation.1.0/src/elevation_v2.c
  codebase/superdarn/src.lib/tk/fitacf.2.5/include/fitblk.h
  codebase/superdarn/src.lib/tk/fitacf.2.5/src/do_fit.c
  codebase/superdarn/src.lib/tk/fitacf_v3.0/include/fit_structures.h
  codebase/superdarn/src.lib/tk/fitacf_v3.0/include/fitacftoplevel.h
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/determinations.c
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/determinations.h
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/fitacftoplevel.c
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/fitting.c
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/fitting.h
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/leastsquares.c
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/preprocessing.c
  codebase/superdarn/src.lib/tk/fitacf_v3.0/src/preprocessing.h
Labels: Scientist input, enhancement

#383 adding branching docs
  docs/dev/branching.md
Labels: documentation

#373 Fix/make grid
  codebase/superdarn/src.bin/tk/tool/make_grid.2.0/doc/make_grid.doc.xml
  codebase/superdarn/src.bin/tk/tool/make_grid.2.0/make_grid.c
  docs/user_guide/make_grid.md
Labels: Error/Warning checks, bug, enhancement

#385 Developer Workflow Documentation testing
  docs/dev/testing.md
Labels: documentation
