Repository SuperDARN/rst, pull requests merged in 2021-04, with the labels that each got.

#403 Fixing bug in time_plot where user-defined color keys did not work
  codebase/superdarn/src.lib/tk/binplotlib.1.0/src/key.c
Labels: bug

#404 fixing typos in copyright docs
  docs/developers_guide/copyright_license.md
Labels: documentation

#408 Fixing pointer freeing error in hmb_plot and pc_plot
  codebase/superdarn/src.bin/tk/plot/hmb_plot.1.6/hmb_plot.c
  codebase/superdarn/src.bin/tk/plot/pc_plot.1.6/pc_plot.c
Labels: bug

#409 Fixing postscript output for various plotting binaries
  codebase/analysis/src.bin/cdf/istp_plot.1.11/istp_plot.c
  codebase/superdarn/src.bin/tk/plot/fov_plot.1.10/fov_plot.c
  codebase/superdarn/src.bin/tk/plot/hmb_plot.1.6/hmb_plot.c
  codebase/superdarn/src.bin/tk/plot/pc_plot.1.6/pc_plot.c
  codebase/superdarn/src.bin/tk/plot/time_plot.1.8/time_plot.c
  codebase/superdarn/src.bin/tk/plot/vec_plot.1.9/vec_plot.c
Labels: bug

#405 Update license/copyright FAQ
  docs/developers_guide/copyright_license.md
Labels: documentation, high priority

#411 Fix elevation angle error bounds in FITACF2.5
  codebase/superdarn/src.lib/tk/fitacf.2.5/src/do_fit.c
Labels: bug
