Repository SuperDARN/rst, pull requests merged in 2024-05, with the labels that each got.

#597 Updating fitacfclientgui to add support for toggling between gate and slant range
  codebase/superdarn/src.bin/tk/tcpip/fitacfclientgui.1.0/doc/fitacfclientgui.doc.xml
  codebase/superdarn/src.bin/tk/tcpip/fitacfclientgui.1.0/fitacfclientgui.c
Labels: enhancement

#602 Fixing bug in time_plot when plotting snd data
  codebase/superdarn/src.bin/tk/plot/time_plot.1.8/time_plot.c
Labels: bug

#595 Fixing array indexing bugs in make_sim and sim_real
  codebase/superdarn/src.bin/tk/tool/make_sim.1.0/make_sim.c
  codebase/superdarn/src.bin/tk/tool/sim_real.1.0/sim_real.c
Labels: bug

#574 Elevation statistics tool
  codebase/superdarn/src.bin/tk/tool/find_elvstat.1.0/doc/find_elvstat.doc.xml
  codebase/superdarn/src.bin/tk/tool/find_elvstat.1.0/find_elvstat.c
  codebase/superdarn/src.bin/tk/tool/find_elvstat.1.0/makefile
  codebase/superdarn/src.lib/tk/elvstat.1.0/doc/elvstat.doc.xml
  codebase/superdarn/src.lib/tk/elvstat.1.0/include/elvstat.h
  codebase/superdarn/src.lib/tk/elvstat.1.0/src/get_fit_elv_stat.c
  codebase/superdarn/src.lib/tk/elvstat.1.0/src/makefile
Labels: feature

#606 Modifying field_plot to mark the radar location with a dot
  codebase/superdarn/src.bin/tk/plot/field_plot.1.12/doc/field_plot.doc.xml
  codebase/superdarn/src.bin/tk/plot/field_plot.1.12/field_plot.c
Labels: enhancement

#600 Fixing bug in GridTableWrite
  codebase/superdarn/src.lib/tk/gtablewrite.1.9/src/gtablewrite.c
Labels: bug

#614 Modifying FitReadRadarScan to store sky noise in RadarBeam structure rather than search noise
  codebase/superdarn/src.lib/tk/fit.1.35/src/fitscan.c
  docs/references/general/grid.md
  docs/references/general/map.md
Labels: enhancement, help wanted, Scientist input
